Update failure.yml

diff --git a/.github/workflows/failure.yml b/.github/workflows/failure.yml
--- a/.github/workflows/failure.yml
+++ b/.github/workflows/failure.yml
@@ -90,4 +90,18 @@ jobs:
                                  -H "Accept: application/vnd.github.v3+json" \
                                  https://api.github.com/repos/naregkar/AutoMerge/contents/.github/version | jq -r '.content')
 
-                 echo "master_version=$(echo $contentMaster | base64 -d)" >> $GITHUB_ENV         
+                 echo "master_version=$(echo $contentMaster | base64 -d)" >> $GITHUB_ENV
+                 
+                 
+        - name: Compare values and assess the mergeability based on the version files
+          run: |
+               echo 'pr version is:' $pr_version
+               echo 'master version is:' $master_version
+
+               if [[ "$pr_version" == "$master_version" ]]; then
+                 echo 'Matching PR and master versions.'
+               else
+                 echo 'PR branch planned for a future release. Cannot merge.'
+                 exit 1
+               fi
+
