Update failure.yml

diff --git a/.github/workflows/failure.yml b/.github/workflows/failure.yml
--- a/.github/workflows/failure.yml
+++ b/.github/workflows/failure.yml
@@ -98,11 +98,11 @@ jobs:
                     #exit 1
                   fi
                   
-        - name: Validate PR Title
-          run: |
-                echo ${{ steps.validatePRTitle.outputs.result }}
-                if [[ "${{ steps.validatePRTitle.outputs.result }}" == "fail" ]]; then
-                  exit 1
-                else
-                  echo ${{ steps.validatePRTitle.outputs.result }}
-                fi
+        #- name: Validate PR Title
+        #  run: |
+        #        echo ${{ steps.validatePRTitle.outputs.result }}
+        #        if [[ "${{ steps.validatePRTitle.outputs.result }}" == "fail" ]]; then
+        #          exit 1
+        #        else
+        #          echo ${{ steps.validatePRTitle.outputs.result }}
+        #        fi
